In [1]:
from datetime import datetime
from GameBoard import GameBoard
from Agent import Agent
from Random_Agent import RandomAgent

In [2]:
def check_win(board: GameBoard):
    return board.get_max_tile() >= 2048


int_to_string = ['UP', 'DOWN', 'LEFT', 'RIGHT']

In [ ]:
agent: Agent
board: GameBoard
agent = RandomAgent()
board = GameBoard()
done = False
moves = 0
board.render()
start = datetime.now()
while not done:
    action = agent.play(board)
    print('Next Action: "{}"'.format(
        int_to_string[action]), ',   Move: {}'.format(moves))
    done = board.play(action)
    done = done or check_win(board)
    board.render()
    moves += 1

print('\nTotal time: {}'.format(datetime.now() - start))
print('\nTotal Moves: {}'.format(moves))
if check_win(board):
    print("WON THE GAME!!!!!!!!")
else:
    print("BOOOOOOOOOO!!!!!!!!!")


In [3]:

board = GameBoard()


In [6]:
board.grid

array([[0., 0., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.],
       [0., 0., 0., 0.]])

In [18]:
for row in range(board.grid.shape[0] - 1):
    print(board.grid[row] - board.grid[row + 1])

[ 0.  0. -2.  0.]
[ 0.  0.  2. -2.]
[0. 0. 0. 2.]


In [27]:
import numpy
numpy.array([board.grid[:, row]  for row in range(board.grid.shape[0] )])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.]])

In [26]:
import numpy
numpy.array([board.grid[:, row] - board.grid[:, row + 1] for row in range(board.grid.shape[0] - 1)])


array([[ 0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  0.],
       [ 0.,  2., -2.,  0.]])

In [12]:
from array import ArrayType
import dataclasses
import numpy as np
from expectimax_agent import ExpectiMaxAgent

class mock:
    grid = None
    def __init__(self, grid) -> None:
        self.grid = grid
    
a1 = np.array(
    [[4 ,      8  ,     4  ,     2],
     [8    ,   4 ,      2      , 4],
    [32  ,    16     , 32    ,   2],
    [ 2    , 128 ,     64     , 16],]
)
values = []
h = ExpectiMaxAgent().heuristic_utility(mock(a1), -2)
values.append(h)

In [16]:
a2 = np.array(
    [[0,       0,       0,       2],
     [16,       8,       0,       0],
     [16,      8,      0,       0],
    [32,     2,      4 ,     0]]
)

h2 = ExpectiMaxAgent().heuristic_utility(mock(a2), -2)
h2


-0.04755238992082798

In [17]:
a2 = np.array(
    [[2,       0,       0,       0],
     [16,       8,       0,       0],
     [16,      8,      0,       0],
    [32,     2,      4 ,     0]]
)

h2 = ExpectiMaxAgent().heuristic_utility(mock(a2), -2)
h2

-0.01819155471585023

In [26]:
a2 = np.array(
    [[0,       0,       0,       0],
     [0,       0,       0,       0],
     [32,      16,      0,       0],
    [32,     2,      4 ,     2]]
)

h2 = ExpectiMaxAgent().heuristic_utility(mock(a2), -8)
h2

-72.12494584051292

In [45]:
smoth = -4
a2 = np.array(  # LEFT
    [[128,      16,       8,       2],
    [32,       16,       2,       0],
    [ 4,       0 ,      0  ,     0],
    [0,       0 ,      0,       0]]
)

h2 = ExpectiMaxAgent().heuristic_utility(mock(a2), smoth)
print(h2)
a2 = np.array(  # LEFT
    [[128,      16,       8,       2],
    [32,       16,       2,       0],
    [ 4,       0 ,      0  ,     0],
    [0,       0 ,      0,       0]]
)

h2 = ExpectiMaxAgent().heuristic_utility(mock(a2), smoth)
print(h2)


pow_grid = np.power(a2, 2)
result = pow_grid.sum()
1/result

-5.271204582799327e-07
-0.0002275341936827096


3.572551373288748e-06

In [100]:

[int((16 - i) / 2.286) for i in range(16)]

[6, 6, 6, 5, 5, 4, 4, 3, 3, 3, 2, 2, 1, 1, 0, 0]

In [114]:
[int((16 - i) / 2.1) for i in range(16)]

[7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0, 0]

In [188]:
# IZQ
[np.digitize(16-i, [0,0,0,2,8,13]) for i in range(16)]

[6, 6, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3]

In [182]:
# DER
[np.digitize(16-i, [0,0,0,0,0,16]) for i in range(16)]

[6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [133]:
loses=[(767, 90.4313862323761), (855, 89.46138858795166), (696, 65.59150767326355), (978, 52.37831497192383), (1007, 51.1624116897583), (1080, 57.11292314529419), (1069, 56.39139795303345), (512, 54.60288429260254), (977, 51.015414237976074), (944, 48.8709716796875), (971, 51.57047510147095), (746, 39.53931736946106), (955, 48.72100758552551), (1011, 99.13407325744629), (964, 52.651461362838745), (835, 89.35092091560364), (790, 43.585384368896484), (955, 52.56012749671936), (980, 97.99853444099426), (996, 55.79466152191162), (879, 46.737234354019165), (898, 47.44594883918762), (1088, 115.90059733390808), (842, 44.62632751464844), (930, 50.2663369178772), (959, 51.71756958961487)]