In [1]:
import numpy as np
from Tic_Tac_Toe import TicTacToe
from Agent import Agent
from Random_Agent import RandomAgent
from Agent_Minimax import AgentMinimax

def print_winner(winner: int):
    if winner == 0:
        print("Empate")
    elif winner == 1:
        print("Gano jugador 1")
    elif winner == 2:
        print("Gano jugador 2")
    else:
        print("Paso algo raro")
    
agent1 = AgentMinimax(1) #0
agent2 = RandomAgent(2) #X
agents = [agent1, agent2]

tic_tac_toe = TicTacToe()
done = False
winner = -1
i = 0
while not done:
    i = (i+1) % 2
    pos, value = agents[i].policy(tic_tac_toe)
    done, winner = tic_tac_toe.play(pos, agents[i].player)
    tic_tac_toe.render()
print_winner(winner)


---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   O   ||   -   |
---------------------------
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   O   ||   X   |
---------------------------
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   O   ||   -   |
---------------------------
|   -   ||   O   ||   X   |
---------------------------
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   O   ||   -   |
---------------------------
|   X   ||   O   ||   X   |
---------------------------
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   O   ||   O   ||   -   |
---------------------------
|   X   ||   O   ||   X   |
---------------------------
--------------------

In [63]:
def print_winner(winner: int):
    if winner == 0:
        print("Empate")
    elif winner == 1:
        print("Gano jugador 1")
    elif winner == 2:
        print("Gano jugador 2")
    else:
        print("Paso algo raro")

In [71]:
agent1 = RandomAgent(1) #0
agent2 = RandomAgent(2) #X
agents = [agent1, agent2]

tic_tac_toe = TicTacToe()
done = False
winner = -1
i = 0
while not done:
    i = (i+1) % 2
    pos, value = agents[i].policy(tic_tac_toe)
    done, winner = tic_tac_toe.play(pos, agents[i].player)
    tic_tac_toe.render()
print_winner(winner)

---------------------------
|   -   ||   O   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
---------------------------
|   -   ||   O   ||   -   |
---------------------------
|   -   ||   -   ||   X   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
---------------------------
|   -   ||   O   ||   O   |
---------------------------
|   -   ||   -   ||   X   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
---------------------------
|   -   ||   O   ||   O   |
---------------------------
|   X   ||   -   ||   X   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
---------------------------
|   -   ||   O   ||   O   |
---------------------------
|   X   ||   -   ||   X   |
---------------------------
|   -   ||   O   ||   -   |
---------------------------
--------------------

In [73]:
agent1 = AgentMinimax(1) #0
agent2 = RandomAgent(2) #X
agents = [agent1, agent2]

tic_tac_toe = TicTacToe()
done = False
winner = -1
i = 0
while not done:
    i = (i+1) % 2
    pos, value = agents[i].policy(tic_tac_toe)
    done, winner = tic_tac_toe.play(pos, agents[i].player)
    tic_tac_toe.render()
print_winner(winner)


---------------------------
|   O   ||   -   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------
|   -   ||   -   ||   -   |
---------------------------


TypeError: 'NoneType' object is not subscriptable

In [38]:
grid = np.zeros((3, 3), dtype=np.int)
grid[0][0] = 1
grid[1][1] = 1
grid[2][2] = 1
grid = grid.transpose()
print(grid)
print(grid[0])
print(grid[1])
print(grid[2])
[i for i in range(1,3)]


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 0 0]
[0 1 0]
[0 0 1]


C:\Users\chelo\AppData\Local\Temp\ipykernel_23672\1008204085.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  grid = np.zeros((3, 3), dtype=np.int)


[1, 2]

In [59]:
for i in (1,2):
    print(f"i: {i} = {i%2}")

i: 1 = 1
i: 2 = 0
